amazon:
  s3:
    bucket-name: ${BUCKET_NAME}
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
kafka:
  bootstrap-servers: ['kafka:9092']
  group-name:
    input: ${KAFKA_INPUT_GROUP_NAME}
  topic-name:
    input: ${KAFKA_INPUT_TOPIC}
    output: ${KAFKA_OUTPUT_TOPIC}
